// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/components/App.vue')['default']
    copy: typeof import('./src/components/svg/SVGOrganism copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SVG: typeof import('./src/components/svg/SVG.vue')['default']
    SVGAtom: typeof import('./src/components/svg/SVGAtom.vue')['default']
    SVGFireship: typeof import('./src/components/svg/SVGFireship.vue')['default']
    SVGG: typeof import('./src/components/svg/SVGG.vue')['default']
    SVGMolecule: typeof import('./src/components/svg/SVGMolecule.vue')['default']
    SVGOrganism: typeof import('./src/components/svg/SVGOrganism.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
