// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    2: typeof import('./src/components/svg/SVGFireship copy 2.vue')['default']
    3: typeof import('./src/components/svg/SVGFireship copy 3.vue')['default']
    App: typeof import('./src/components/App.vue')['default']
    copy: typeof import('./src/components/svg/SVGFireship copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SVGAtom: typeof import('./src/components/svg/SVGAtom.vue')['default']
    SVGAtoms: typeof import('./src/components/svg/SVGAtoms.vue')['default']
    SVGFireship: typeof import('./src/components/svg/SVGFireship.vue')['default']
    SVGMolecule: typeof import('./src/components/svg/SVGMolecule.vue')['default']
    SVGMolecules: typeof import('./src/components/svg/SVGMolecules.vue')['default']
    SVGOrganism: typeof import('./src/components/svg/SVGOrganism.vue')['default']
    SVGOrganisms: typeof import('./src/components/svg/SVGOrganisms.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
